# Generated by Django 2.2 on 2020-08-15 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20200808_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
