# Generated by Django 2.2 on 2020-09-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_triviagame_usertriviagame'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
