# Generated by Django 2.2 on 2020-09-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_userdetail_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertriviagame',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
