# Generated by Django 2.2 on 2020-09-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_usertriviagame_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertriviagame',
            name='answered_count',
            field=models.IntegerField(default=0),
        ),
    ]
