# Generated by Django 2.2 on 2020-09-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_usertriviagame_answered_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertriviagame',
            name='answered_count',
        ),
    ]
