# Generated by Django 2.2 on 2020-11-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_auto_20201103_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersudokugame',
            name='time',
            field=models.IntegerField(default=1800),
        ),
    ]
