# Generated by Django 2.2 on 2020-11-06 03:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_usersudokugame_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersudokugame',
            name='current_board',
            field=models.CharField(default=datetime.datetime(2020, 11, 6, 3, 12, 30, 196328, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
