# Generated by Django 2.2 on 2020-11-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0013_usersudokugame_current_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersudokugame',
            name='current_board',
            field=models.CharField(default='', max_length=200),
        ),
    ]
