# Generated by Django 2.2 on 2020-11-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0014_auto_20201106_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepuzzlegame',
            name='active',
        ),
        migrations.RemoveField(
            model_name='imagepuzzlegame',
            name='difficulty',
        ),
    ]
