# Generated by Django 2.2 on 2020-11-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0015_auto_20201107_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimagepuzzlegame',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userimagepuzzlegame',
            name='time',
            field=models.IntegerField(default=1800),
        ),
        migrations.AddField(
            model_name='usersudokugame',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertriviagame',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
