# Generated by Django 2.2 on 2020-11-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0018_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
