# Generated by Django 2.2 on 2020-11-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0019_transaction_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('withdrawal', 'w'), ('deposit', 'd')], max_length=10),
        ),
    ]
